Controllers/CreateAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortal.BLL;
using JobPortal.Models;

namespace JobPortal.Controllers
{
    public class CreateAccountController : Controller
    {

        CreateAccountManager createAccountManager = new CreateAccountManager();

        public ActionResult SeekerAccount()
        {
            ViewBag.genderList = GetGenderInfo();
            ViewBag.message = " ";
            return View();
        }

        [HttpPost]
        public ActionResult SeekerAccount(Seeker seeker)
        {
            ViewBag.genderList = GetGenderInfo();
            string message = createAccountManager.InsertSeekerInfo(seeker);
            ViewBag.message = message;
            return View();
        }

        public ActionResult EmployerAccount()
        {
            ViewBag.message = " ";
            return View();
        }

        [HttpPost]
        public ActionResult EmployerAccount(Employer employer)
        {
            string message = createAccountManager.InsertEmployerInfo(employer);
            ViewBag.message = message;
            return View();
        }

        private List<SelectListItem> GetGenderInfo()
        {
            List<Gender> genderList = createAccountManager.GetGenderInfo();
            List<SelectListItem> genders = new List<SelectListItem>();
            foreach (var item in genderList)
            {
                genders.Add(new SelectListItem() { Value = item.ID.ToString(), Text = item.Type });
            }
            return genders;
        }
	}
}

Views/Shared/_Layout.cshtml
@using JobPortal.Models

@{

    dynamic seeker = Session["user"] as Seeker;

    dynamic employer = Session["user"] as Employer;
}



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Job Portal</title>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/Scripts/jquery.dataTables.min.css" rel="stylesheet"/>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />


    <style>
        .field-validation-error {
            color: red;
        }
    </style>

</head>




<body>

    <nav class="navbar navbar-primary navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Job Portal", "Index", "Home", null, new { @class = "navbar-brand" })
               
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" style="font-size: 14px">

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("All Jobs", "ViewAllPostedJobs", "Job")</li>

                    @if (seeker == null && employer == null)
                    {
                        <li>@Html.ActionLink("Create Seeker Account", "SeekerAccount", "CreateAccount")</li>
                        
                        <li>@Html.ActionLink("Create Employer Account", "EmployerAccount", "CreateAccount")</li>
                        
                        
                        <li>@Html.ActionLink("Login", "LoginAccount", "Login")</li>
                        
                    }
                    else if (seeker != null && employer == null)
                    {
                        <li>@Html.ActionLink("Manage Resume", "ManageResume", "Seeker")</li>
                        <li>@Html.ActionLink("Applied Jobs", "SeekerAppliedJobs", "Job")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                        
                    }
                    else if (seeker == null && employer != null)
                    {
                        <li>@Html.ActionLink("Post Job", "EmployerJobPost", "Job")</li>
                        <li>@Html.ActionLink("Your Posted Jobs", "ViewEmployerPostedJobs", "Job")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                    


                    

                </ul>
                

                <ul class="nav navbar-nav navbar-right" style="font-size: 14px">

                    @*<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create Account<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Seeker", "SeekerAccount", "CreateAccount")</li>
                            <li>@Html.ActionLink("Employer", "EmployerAccount", "CreateAccount")</li>

                        </ul>
                    </li>*@
                </ul>
            </div>
        </div>
    </nav>





    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           
            <p>&copy;  Job Portal - All Rights Reserved.</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.1.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>